pipeline:
  name: Linux Deploy
  identifier: Linux_Deploy
  projectIdentifier: New_Terraform_Project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: terraform
        identifier: terraform
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformApply
                  name: TerraformApply_1
                  identifier: TerraformApply_1
                  spec:
                    provisionerIdentifier: terraform_EC2
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            spec:
                              connectorRef: Github_connector
                              gitFetchType: Branch
                              branch: main
                              folderPath: .
                            type: Github
                        providerCredential:
                          type: Aws
                          spec:
                            connectorRef: AWS_connector
                            region: ap-south-1
                            roleArn: ""
                  timeout: 10m
        tags: {}
